security:
  oauth2:
    client:
      client-id: ENC(WJRDLZlPlWkmLu/d+gkeAw==)
      client-secret: ENC(gyOtaeY+fxP8/Rkd3PKm8Q==)
      scope: server

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://albedo-mysql:3306/albedo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

# 直接放行URL
ignore:
  urls:
    - /v2/**
    - /actuator/**
    - /user/info/*
    - /log/**

