spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        # 认证中心
        - id: albedo-auth
          uri: lb://albedo-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - ValidateCodeGatewayFilter
            # 前端密码解密
            - PasswordDecoderFilter
        #系统管理 模块
        - id: albedo-sys
          uri: lb://albedo-sys
          predicates:
            - Path=/sys/**
          filters:
            # 限流配置
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
        #            - name: Hystrix
        #              args:
        #                name: default
        #                fallbackUri: 'forward:/fallback'
        # 代码生成模块
        - id: albedo-gen
          uri: lb://albedo-gen
          predicates:
            - Path=/gen/**
        - id: albedo-quartz
          uri: lb://albedo-quartz
          predicates:
            - Path=/quartz/**

security:
  encode:
    # 前端密码密钥，必须16位
    key: 'somewhere-albedo'

# 不校验验证码终端
ignore:
  clients:
    - swagger
