
logging:
  level:
    ROOT: INFO
    com.albedo.java: DEBUG
# ===================================================================
# Albedo specific properties
# ===================================================================

application:
  developMode: true
  adminPath: /a
  jedisKeyPrefix: albedoBootWebApp
  className: com.albedo.java
  logPath: target/.logs/${spring.application.name}
