
logging:
  level:
    ROOT: DEBUG
    com.albedo.java: DEBUG
    org.springframework.cloud.gateway: DEBUG
# ===================================================================
# Albedo specific properties
# ===================================================================

application:
  developMode: true
  adminPath: /a
  jedisKeyPrefix: albedoBootWebApp
  className: com.albedo.java
